networks:
  rnk_nw: {}  # Custom network name

volumes:
  mysql_vol:  # Custom volume for MySQL data

services: 
  mysql_image: # mysql Image building
    build:
      context: /home/ec2-user/docker-volumes-compose/mysql/
      dockerfile: Dockerfile
    image: mysql:1.0.0

  backend_image: # backend Image building
    build:
      context: /home/ec2-user/docker-volumes-compose/backend/
      dockerfile: Dockerfile
    image: backend:1.0.0

  frontend_image: # frontend Image building
    build:
      context: /home/ec2-user/docker-volumes-compose/frontend/
      dockerfile: Dockerfile
    image: frontend:1.0.0

 